# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

# https://github.com/pre-commit/pre-commit/issues/2586
# default_language_version:
#   python: python3.11
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: check-docstring-first
      - id: check-added-large-files
      - id: check-yaml
      - id: debug-statements
      - id: check-merge-conflict

      - id: end-of-file-fixer

  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.1.5
    hooks:
      # Run the linter.
      - id: ruff
        args: [ --fix ]
      # Run the formatter.
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-mypy # https://github.com/python/mypy  # Add static typing checks
    rev: 'v1.10.0'
    hooks:
    -   id: mypy
        args: [--config-file, ./mypy.ini, --ignore-missing-imports]

  # Do not use cache to prevent conflict on pipeline
  # https://github.com/python-poetry/poetry/issues/8189
  - repo: https://github.com/python-poetry/poetry
    rev: '1.6.0'  # add version here
    hooks:
      - id: poetry-check
        args: [--no-cache]
        # language_version: python3.11
      - id: poetry-lock
        args: [--no-cache]
        # language_version: python3.11

  - repo: https://github.com/python-poetry/poetry-plugin-export
    rev: '1.6.0'  # add version here
    hooks:
      - id: poetry-export
        args: ["--no-cache", "-f", "requirements.txt", "-o", "requirements.txt"]
        # language_version: python3.11

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.5
    hooks:
      - id: bandit  # Nb: .bandit file is ignore by pre-commit hook
        # args: [--skip, "B320,B410", --recursive, clumper]


  - repo: https://github.com/semgrep/semgrep
    rev: v1.48.0
    hooks:
      - id: semgrep
        # This uses the Python "hook" in .pre-commit-hooks.yaml and setup.py.
        # alt: use 'repo: local', and 'language: docker', which can use
        # the very latest docker image, which is nice, but is far slower.

        language: python


        # Both the .semgrepignore file and the --exclude option
        # do nothing because the target files are passed
        # explicitly on the command line by pre-commit!
        args: [
            # use osemgrep!
            #"--experimental",
            # use jsonnet!
            # "--config", "semgrep.jsonnet",
            # classic flag to use in CI or pre-commit, return error code if findings
            "--error",
            #"--verbose",
            "--skip-unknown-extensions",
            # "--metrics=off",
          ]

  - repo: https://github.com/bridgecrewio/checkov
    rev: 3.2.83
    hooks:
      - id: checkov_diff
        args: ["--skip-check", "CKV_GITLABCI_2", "-f"]
      - id: checkov_secrets
